name: pytest unittest

on:
  pull_request:
      branches: [ "develop", "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python pyhealth/unittests/test_datasets/test_mimic3.py 
          cd pyhealth/unittests
          pytest -v
      - name: Test with pytest
        run: |
          ls ~
          ls ~/.cache
          ls ~/.cache/datasets
      - name: cache pickled data
        uses: actions/upload-artifact@v3
        with:
          name: pyhealth cache
          path: ~/.cache/datasets
      - name: cache pickled data
        uses: actions/upload-artifact@v3
        with:
          name: pyhealth cache
          path: ~/.cache/medcode
