name: Python package

on:
  pull_request:
      branches: [ "develop", "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          echo "cd pyhealth/unittest"
          ls pyhealth
          pytest -v
          

