name: pytest unittest

on:
  pull_request:
      branches: [ "develop", "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: look
        run: |
          ls -al
          ls -al ..
          ls /
          ls ~/
      - name: cache datasets
        uses: actions/cache@v3
        with:
          path: /.cache/pyhealth/datasets
      - name: Test with pytest
        run: |
          cd pyhealth/unittests
          pytest -v
